CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

TARGET = human

SRC = main.cpp \
	HumanA.cpp \
	HumanB.cpp \
	Weapon.cpp \

OBJ = $(SRC:.cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(TARGET)

re: fclean all

.PHONY: all clean fclean re